#!/usr/bin/env python
"""Detect drift between the ORM models and the authoritative Alembic schema.

Production and local stacks build the schema with ``alembic upgrade head``.
The SQLAlchemy models remain the application mapping of that schema, so CI
compares both representations and requires zero drift.

What this does
--------------
Builds a throwaway database from the migrations (``alembic upgrade head``),
runs Alembic's ``compare_metadata`` against the live ORM ``Base.metadata`` with
``compare_type`` + ``compare_server_default`` enabled, and prints a categorised
inventory of every difference. Exits non-zero if the total exceeds
``DRIFT_BASELINE``. The current zero baseline makes any difference a regression.

Reconcile direction per category (for the multi-PR cleanup that follows):
  modify_default   -> add server_default to the models to match the migrations
  modify_nullable  -> models are the stricter/intended truth; tighten migrations
  modify_type      -> adopt tz-aware DateTime + the migration's lengths/numerics
  add/remove_*     -> bring the migrations up to the current models
Each is a deliberate, reviewed change against a live schema, not autogenerated.

Usage
-----
    # Needs a role that can CREATE DATABASE; builds+drops a scratch DB itself:
    DRIFT_PG_ADMIN_URL=postgresql://trader:pass@localhost:5432/postgres \\
        python scripts/db/check_schema_drift.py

    # Or compare an already-migrated database and skip the build/teardown:
    DRIFT_DB_URL=postgresql://trader:pass@localhost:5432/vm_drift \\
        python scripts/db/check_schema_drift.py --no-setup
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Recorded total drift, ratcheted down as categories are reconciled. History:
# 224 (audit) -> 156 (model server defaults) -> 154 (lean) -> 93 (NOT NULL)
# -> 42 (types) -> 37 (columns) -> 0 (indexes/FKs/constraints).
DRIFT_BASELINE = 0
_MODIFY_DIFF_MIN_LENGTH = 7

REPO_ROOT = Path(__file__).resolve().parents[2]
for _lib in ("lib_common", "lib_strategy", "lib_application"):
    _lib_path = REPO_ROOT / "libs" / "python" / _lib
    if _lib_path.is_dir() and str(_lib_path) not in sys.path:
        sys.path.insert(0, str(_lib_path))

from alembic import command  # noqa: E402
from alembic.autogenerate import compare_metadata  # noqa: E402
from alembic.config import Config  # noqa: E402
from alembic.migration import MigrationContext  # noqa: E402
from sqlalchemy import create_engine, text  # noqa: E402

from lib_application.db.models import Base  # noqa: E402

_SCRATCH_DB = "vm_schema_drift_check"
_EXTENSIONS = ("pg_trgm", "btree_gin", '"uuid-ossp"')


def _flatten(diffs: list) -> list:
    """compare_metadata returns single tuples and lists of tuples; flatten."""
    out: list = []
    for diff in diffs:
        if isinstance(diff, list):
            out.extend(diff)
        else:
            out.append(diff)
    return out


def _label(item: tuple) -> str:
    """Human-readable 'table.column (a -> b)' style label for one diff tuple."""
    op = item[0]
    if op in ("add_table", "remove_table"):
        return str(item[1].name)
    if op in ("add_column", "remove_column"):
        return f"{item[2]}.{item[3].name}"
    if op.startswith("modify_"):
        base = f"{item[2]}.{item[3]}"
        if len(item) >= _MODIFY_DIFF_MIN_LENGTH:
            return f"{base}  ({item[5]} -> {item[6]})"
        return base
    obj = item[1]
    name = getattr(obj, "name", None)
    table = getattr(obj, "table", None)
    return f"{getattr(table, 'name', table) or ''}: {name or obj}".strip(": ")


def _migrated_db_url(admin_url: str) -> str:
    """Create + migrate a throwaway database, return its URL."""
    base, _, _ = admin_url.rpartition("/")
    target = f"{base}/{_SCRATCH_DB}"
    admin = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin.connect() as conn:
        conn.execute(text(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}"'))
        conn.execute(text(f'CREATE DATABASE "{_SCRATCH_DB}"'))
    admin.dispose()

    scratch = create_engine(target, isolation_level="AUTOCOMMIT")
    with scratch.connect() as conn:
        for ext in _EXTENSIONS:
            conn.execute(text(f"CREATE EXTENSION IF NOT EXISTS {ext}"))
    scratch.dispose()

    cfg = Config(str(REPO_ROOT / "scripts" / "db" / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO_ROOT / "scripts" / "db" / "alembic"))
    os.environ["DATABASE_URL"] = target
    command.upgrade(cfg, "head")
    return target


def _drop_scratch(admin_url: str) -> None:
    admin = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin.connect() as conn:
        conn.execute(text(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}"'))
    admin.dispose()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-setup",
        action="store_true",
        help="Compare DRIFT_DB_URL directly (already at head); skip building a scratch DB.",
    )
    args = parser.parse_args()

    admin_url = os.environ.get("DRIFT_PG_ADMIN_URL")
    if args.no_setup:
        db_url = os.environ.get("DRIFT_DB_URL")
        if not db_url:
            print("ERROR: --no-setup requires DRIFT_DB_URL", file=sys.stderr)
            return 2
    else:
        if not admin_url:
            print(
                "ERROR: set DRIFT_PG_ADMIN_URL (a postgres URL that can CREATE DATABASE), "
                "or use --no-setup with DRIFT_DB_URL.",
                file=sys.stderr,
            )
            return 2
        db_url = _migrated_db_url(admin_url)

    try:
        engine = create_engine(db_url)
        with engine.connect() as conn:
            ctx = MigrationContext.configure(
                conn,
                opts={"compare_type": True, "compare_server_default": True},
            )
            diffs = _flatten(compare_metadata(ctx, Base.metadata))
        engine.dispose()
    finally:
        if not args.no_setup and admin_url:
            _drop_scratch(admin_url)

    cats: Counter[str] = Counter()
    by_cat: dict[str, list[str]] = defaultdict(list)
    for item in diffs:
        cats[item[0]] += 1
        by_cat[item[0]].append(_label(item))

    print("=== Model <-> migration drift inventory ===")
    for op, count in cats.most_common():
        print(f"\n## {op}: {count}")
        for label in by_cat[op]:
            print(f"   - {label}")

    total = sum(cats.values())
    print(f"\nTOTAL drift: {total}  (baseline {DRIFT_BASELINE})")
    if total > DRIFT_BASELINE:
        print(
            f"FAIL: drift grew by {total - DRIFT_BASELINE} past the baseline. "
            "Reconcile the new diff or justify raising DRIFT_BASELINE.",
            file=sys.stderr,
        )
        return 1
    if total < DRIFT_BASELINE:
        print(
            f"Drift is {DRIFT_BASELINE - total} below baseline — lower DRIFT_BASELINE "
            f"to {total} in this file to lock in the reduction."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
