"""decision_contexts provenance

Revision ID: 0030_decision_contexts
Revises: 0029_tz_aware_dispatch_ts
Create Date: 2026-06-25 10:46:00.181909
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0030_decision_contexts"
down_revision = "0029_tz_aware_dispatch_ts"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_contexts",
        sa.Column(
            "context_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("signal_id", sa.String(length=100), nullable=False),
        sa.Column("instr_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.String(length=50), nullable=True),
        sa.Column("symbol", sa.String(length=50), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("pipeline_version", sa.String(length=20), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("alpha_core", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("alpha_raw", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("score_standardized", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("p_agg", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("score_value", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("regime", sa.String(length=30), nullable=True),
        sa.Column("vix_level", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("iv_rank", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("realized_vol", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("liquidity_score", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("news_sentiment", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=True),
        sa.Column("abstain_reason", sa.String(length=100), nullable=True),
        sa.Column("feature_snapshot", sa.JSON(), nullable=True),
        sa.Column("factor_contributions", sa.JSON(), nullable=True),
        sa.Column("stale_inputs", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instr_id"],
            ["instruments.instr_id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.strategy_id"],
        ),
        sa.PrimaryKeyConstraint("context_id"),
    )
    op.create_index(
        "ix_decision_context_instr_created",
        "decision_contexts",
        ["instr_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_contexts_created_at"), "decision_contexts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_decision_contexts_run_id"), "decision_contexts", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_decision_contexts_signal_id"), "decision_contexts", ["signal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decision_contexts_signal_id"), table_name="decision_contexts")
    op.drop_index(op.f("ix_decision_contexts_run_id"), table_name="decision_contexts")
    op.drop_index(op.f("ix_decision_contexts_created_at"), table_name="decision_contexts")
    op.drop_index("ix_decision_context_instr_created", table_name="decision_contexts")
    op.drop_table("decision_contexts")
    # ### end Alembic commands ###
